server:
  port: 8084
spring:
  application:
    name: NOTIFICATION-SERVICE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    hostname: localhost
