server:
  port: 8081
management:
  endpoints:
    web:
      exposure:
        include: prometheus
spring:
  application:
    name: PRODUCT-SERVICE
  data:
    mongodb:
      uri : mongodb://127.0.0.1:27017/product-service
  zipkin:
    base-url: http://localhost:9411
  sleuth:
    sampler:
      probability: 1.0

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:password@localhost:8761/eureka/
  instance:
    hostname: localhost